[Plugins]
blurEnabled=true
wobblyWindowsEnabled=true
magiclampEnabled=true

[Effect-blur]
BlurStrength=4
NoiseStrength=0

[Script-krohnkite]
enableBTreeLayout=true
screenGapBottom=16
screenGapLeft=16
screenGapRight=16
screenGapTop=16
tileLayoutGap=16
