color_theme = "kosame"
theme_background = False
truecolor = True
graph_symbol = "braille"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_gradient = True
show_uptime = True
check_temp = True
draw_clock = "%H:%M"
mem_graphs = True
show_swap = True
show_disks = True
net_auto = True
