conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 0,
    cpu_avg_samples = 4,
    default_color = 'c8e1e8',
    draw_borders = false,
    draw_outline = false,
    draw_shades = false,
    gap_x = 200,
    gap_y = 280,
    minimum_width = 200,
    maximum_width = 200,
    net_avg_samples = 4,
    no_buffers = true,
    out_to_console = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    update_interval = 2.0,
    double_buffer = true,
    uppercase = false,
    use_xft = true,
    xftalpha = 1,
}

conky.text = [[
${color #c8e1e8}${font :size=40}${time %H:%M}${font}${color}
${color #c8e1e8}${font :size=13}${time %a, %b %d %Y}${font}${color}
${color #9ab1b8}---------------------${color}
${font :size=12}${color #bedfed}CPU  ${color #c8e1e8}${cpu cpu0}%
${color #bedfed}RAM  ${color #c8e1e8}${memperc}%
${color #bedfed}DISK ${color #c8e1e8}${fs_used_perc /}%
${color #9ab1b8}---------------------${color}
${color #bedfed}UP   ${color #c8e1e8}${upspeed}
${color #bedfed}DOWN ${color #c8e1e8}${downspeed}
${font}${color}
]]
